[package]
name = "schatter-client"
version = "0.1.0"
edition = "2021"

[dependencies]
nannou_osc = "0.18.0"
smart-leds = "0.3.0"
colored = "2.0"
rand = "0.8.3"
[target.'cfg(target_arch = "arm")'.dependencies]
ws281x-rpi = "0.0.1"

[package.metadata.cross.target.armv7-unknown-linux-gnueabihf]
pre-build = ["apt-get update && apt-get install --assume-yes libclang-dev clang"]
