[package]
name = "schatter-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.18.1"
nannou_osc = "0.18.0"
smart-leds = "0.3.0"
[target.'cfg(target_arch = "arm")'.build-dependencies]
ws281x-rpi = "0.0.1"

[package.metadata.cross.target.armv7-unknown-linux-gnueabihf]
pre-build = ["apt-get update && apt-get install --assume-yes libclang-dev clang"]
